import {
  FETCH_CAT_SUCCESS,
  FETCH_CAT_ERROR,
  FETCH_CAT_REQUEST,
  fetchCat,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_SUCCESS,
  ADOPT_CAT_ERROR,
  adoptCat
} from './cat';

import {
  FETCH_DOG_SUCCESS,
  FETCH_DOG_ERROR,
  FETCH_DOG_REQUEST,
  fetchDog,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_SUCCESS,
  ADOPT_DOG_ERROR,
  adoptDog
} from './dog';

export default {
  FETCH_CAT_SUCCESS,
  FETCH_CAT_ERROR,
  FETCH_CAT_REQUEST,
  fetchCat,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_SUCCESS,
  ADOPT_CAT_ERROR,
  adoptCat,
  FETCH_DOG_SUCCESS,
  FETCH_DOG_ERROR,
  FETCH_DOG_REQUEST,
  fetchDog,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_SUCCESS,
  ADOPT_DOG_ERROR,
  adoptDog
};